// This file is automatically generated. DO NOT MODIFY!

package lumina

func (*DecompilePacket) getType() PacketType {
	return PKT_DECOMPILE
}

func (*DecompilePacket) getResponseType() PacketType {
	return PKT_DECOMPILE_RESULT
}

func (this *DecompilePacket) readFrom(r Reader) (err error) {
	// Field this.Opaque
	// Slice []byte
	var v1 uint32
	if v1, err = readUint32(r); err != nil {
		return
	}
	this.Opaque = make([]byte, v1)
	if err = readBytes(r, this.Opaque); err != nil {
		return
	}
	return
}

func (this *DecompilePacket) writeTo(w Writer) (err error) {
	// Field this.Opaque
	// Slice []byte
	if len(this.Opaque) > 0x7FFFFFFF {
		err = errTooLong
		return
	}
	var v1 = uint32(len(this.Opaque))
	if err = writeUint32(w, v1); err != nil {
		return
	}
	if err = writeBytes(w, this.Opaque); err != nil {
		return
	}
	return
}
