// This file is automatically generated. DO NOT MODIFY!

package lumina

func (this *PatternId) ReadFrom(r Reader) (err error) {
	// Field this.Type
	// Basic uint32
	// Typed PatternType
	var v1 uint32
	if v1, err = readUint32(r); err != nil {
		return
	}
	this.Type = PatternType(v1)
	// Field this.Data
	// Slice []byte
	var v2 uint32
	if v2, err = readUint32(r); err != nil {
		return
	}
	this.Data = make([]byte, v2)
	if err = readBytes(r, this.Data); err != nil {
		return
	}
	return
}

func (this *PatternId) WriteTo(w Writer) (err error) {
	// Field this.Type
	// Basic uint32
	// Typed PatternType
	if err = writeUint32(w, uint32(this.Type)); err != nil {
		return
	}
	// Field this.Data
	// Slice []byte
	if len(this.Data) > 0x7FFFFFFF {
		err = errTooLong
		return
	}
	var v2 = uint32(len(this.Data))
	if err = writeUint32(w, v2); err != nil {
		return
	}
	if err = writeBytes(w, this.Data); err != nil {
		return
	}
	return
}
